<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="utils_tests.py" name="utils_tests.TestIsValid-20200910083745" skipped="0" tests="10" time="0.012" timestamp="2020-09-10T08:37:46">
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_at_maximum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_at_minimum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_between_minimum_and_maximum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_above_maximum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_above_minimum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_below_maximum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_below_minimum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_well_above_maximum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_well_below_minimum" time="0.001" timestamp="2020-09-10T08:37:46"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_empty_string" time="0.003" timestamp="2020-09-10T08:37:46">
		<error message="'NoneType' object has no attribute 'group'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 17, in test_card_number_empty_string
    is_number_valid = utils.is_valid('')
  File "/home/student/Documents/cs3280project1/src/main/python/utils.py", line 26, in is_valid
    if (len(sequence_digits_match.group()) == four_digit_subgroup_card_length):
AttributeError: 'NoneType' object has no attribute 'group'
]]>		</error>
	</testcase>
</testsuite>
