<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="6" file="utils_tests.py" name="utils_tests.TestIsValid-20200911094251" skipped="0" tests="16" time="0.070" timestamp="2020-09-11T09:42:52">
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_empty_string" time="0.001" timestamp="2020-09-11T09:42:51"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_between_minimum_and_maximum" time="0.002" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_above_maximum" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_below_minimum" time="0.002" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_well_above_maximum" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_well_below_minimum" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_letters_and_numbers" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_only_letters" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_wrongly_grouped_card_number_by_dash" time="0.005" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_wrongly_grouped_card_number_by_space" time="0.001" timestamp="2020-09-11T09:42:52"/>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_at_maximum" time="0.023" timestamp="2020-09-11T09:42:51">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 61, in test_card_number_length_at_maximum
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_at_minimum" time="0.002" timestamp="2020-09-11T09:42:52">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 37, in test_card_number_length_at_minimum
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_above_minimum" time="0.013" timestamp="2020-09-11T09:42:52">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 43, in test_card_number_length_one_above_minimum
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
	<testcase classname="utils_tests.TestIsValid" name="test_card_number_length_one_below_maximum" time="0.006" timestamp="2020-09-11T09:42:52">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 55, in test_card_number_length_one_below_maximum
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
	<testcase classname="utils_tests.TestIsValid" name="test_correctly_grouped_card_number_by_dash" time="0.003" timestamp="2020-09-11T09:42:52">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 109, in test_correctly_grouped_card_number_by_dash
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
	<testcase classname="utils_tests.TestIsValid" name="test_correctly_grouped_card_number_by_space" time="0.006" timestamp="2020-09-11T09:42:52">
		<failure message="None is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project1/src/unittest/python/utils_tests.py", line 97, in test_correctly_grouped_card_number_by_space
    self.assertTrue(is_number_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: None is not true
]]>		</failure>
	</testcase>
</testsuite>
